### PR TITLE
Add video support

### PR DESCRIPTION
**Pull request by pjcabrera**
Initial support for recording video or picking videos from the image picker. The code now looks for 'mediaType' to determine if it should take a 'photo' or a 'video'.

Added code to use the option key 'qualityType' to set 'high', 'medium' and 'low' image quality settings. Defaults to 'medium'.

Added code to check the option key 'imageFileType'. imageFileType === 'png' exports the photo as PNG instead of JPG. Defaults to JPG if imageFileType is not set or if set to any value other than 'png'.

Added some error reporting when some steps fail, rather than just writing to the console and either ignoring the error or returning early.

Updated the version number in package.json

### CODE REVIEW

**Comment by natorojr** [comment]
+1

**Comment by marcshilling** [comment]
Planning to review this soon...busy with some real job stuff at the moment :)

**Comment by danlopez** [comment]
+1

**Comment by natorojr** [comment]
Thanks @marcshilling

**Comment by marcshilling** [comment]
Merged! 

There was an issue with the code that moved the video to the temporary directory. It appears that UIImagePickerController does that automatically, so it was deleting the video from the existing directory, and then when it tried to move it it was failing with "file does not exist". I hope I fixed that problem by only performing the move on captured videos.

I also renamed the `qualityType` option to `videoQuality`.

Finally, I changed the response object, so this will be a breaking change. The response is no longer `(didCancel, response) =>`, it's simply `(response)=>` and that object will contain the key `didCancel` if applicable.

README updates to follow...

**Comment by pjcabrera** [comment]
Great! Thanks for letting me know of the API changes. I'll update the calling code at my end when I update the package.json in my project to use your latest version on npm.

**Comment by natorojr** [comment]
Good stuff! Thanks @marcshilling and @pjcabrera. Looking forward to the npm package update

**Comment by marcshilling** [comment]
@natorojr should be published!

**Pull request merged**
