### PR TITLE
Resize tweaks

### PR DESCRIPTION
**Pull request by pedro**
- Use a temp file for the resized images. Otherwise they are displayed under the "pictures" folder within my app files
- Fix path for resized images, make sure it points to the resized file

### CODE REVIEW

**Comment by yfuks** [comment]
Well puting it in the pictures folder was a choice, you should look at the storageOptions that are implemented in **iOS**

```javascript
storageOptions: { // if this key is provided, the image will get saved in the documents directory (rather than a temporary directory)
    skipBackup: true, // image will NOT be backed up to icloud
    path: 'images' // will save image at /Documents/images rather than the root
}
```

Make the same API for android and iOS sure is beneficial. Since iOS was there first try to match it as mutch as possible.

Adding the options to make the user choose will probably do the job.

**Comment by pedro** [comment]
ah interesting! I didn't realize the storageOptions applied to resized images, makes total sense.

Can I add support for a temporary path then? Our use case is to allow users to pick an image from their album, and not have that show anywhere else.

**Comment by pedro** [comment]
eg:

```js
storageOptions: {
  tmp: true // save resized images in a temporary location
}
```

**Comment by yfuks** [comment]
Would be great !

```javascript
storageOptions: {} // if this key is provided, the image will get saved in the documents/picture directory (rather than a temporary directory)
```

Could be good too ! The choice is up to you ! :)

**Comment by pedro** [comment]
ah, doh! missed that :} ok updated to infer from the presence of `storageOptions`.

Thanks!

**Comment by yfuks** [comment]
Sorry for the wait, will merge, add some features and publish a new version

**Comment by pedro** [comment]
no worries! thank you :}

**Pull request merged**
