### PR TITLE
Update UIImagePickerManager.m

### PR DESCRIPTION
**Pull request by Spikef**
Rotate the image for upload to web

### CODE REVIEW

**Comment by marcshilling** [comment]
Can you elaborate on what this is doing and why it's necessary?

**Comment by Spikef** [comment]
Yeah. If you don't have to upload the images you picked to web, it's no necessary to do this. All images are displayed well on iPhone. But after you upload a image to a web server, the image displays a wrong orientation. Imagine that your avatar rotate to left. You can try to take a photo with your camera and upload it to a server. 
Here is a link for your reference.
http://stackoverflow.com/questions/22308921/fix-ios-picture-orientation-after-upload-php

**Comment by Spikef** [comment]
Yeah. If you don't have to upload the images you picked to web, it's no necessary to do this. All images are displayed well on iPhone. But after you upload a image to a web server, the image displays a wrong orientation. Imagine that your avatar rotate to left. You can try to take a photo with your camera and upload it to a server. 
Here is a link for your reference.
http://stackoverflow.com/questions/22308921/fix-ios-picture-orientation-after-upload-php

**Comment by Spikef** [comment]
Yeah. If you don't have to upload the images you picked to web, it's no necessary to do this. All images are displayed well on iPhone. But after you upload a image to a web server, the image displays a wrong orientation. Imagine that your avatar rotate to left. You can try to take a photo with your camera and upload it to a server. 
Here is a link for your reference.
http://stackoverflow.com/questions/22308921/fix-ios-picture-orientation-after-upload-php

**Pull request merged**
