### PR TITLE
Added support of taking photos for Android >=7.0

### PR DESCRIPTION
**Pull request by rusfearuth**
This pull request allows to use this library for Android >= 7.0, because of they use FileProvider for working with files.

### CODE REVIEW

**Comment by mkdotcom** [comment]
Doesn't react-native-image-picker work at all on android >= 6 ? or is it just in improvement?

**Comment by rusfearuth** [comment]
@mkdotcom It doesn't work on taking photos at all on Android >=6

**Comment by mkdotcom** [comment]
@marcshilling this PR should be integrated asap i guess then ? thanks!

**Comment by marcshilling** [comment]
Well first of all, you say you can't take pictures at all on Android > 6? The Example project runs fine on my Android 6.0.1 phone - so why is this necessary? I'm not the biggest Android expert - would be great if @yfuks could chime in!

Apart from that, this PR needs a lot of work before I would merge. Why all the changes to gradle files? Logging should be removed. Your `RealPathUtil.java` declares `package com.reactnative.ivpusic.imagepicker;` which will not work if I merge. 

But all that aside, I'd like to understand why this change is necessary first.

**Comment by rusfearuth** [comment]
@marcshilling Sorry, I'd tested your library for Android >= 7. It didn't work there for taking a picture.

I couldn't build your library with gradle 2.14.2, that's way I'd changed it for 2.2 version and It regenerated gradlew file.

Sorry for logging. I tested your code.

RealPathUrils is much better than what you had before. Your code covered only old several cases for getting real path of images.

Change is necessary if you want use this library for new devices and cover more cases for getting photos for different suppliers.

**Comment by rusfearuth** [comment]
No more logs in it.

**Comment by agustinsivoplas** [comment]
Please solve this issue ASAP. When you try to take a picture the library crashes with android >= 7. The reason is described here: https://developer.android.com/about/versions/nougat/android-7.0-changes.html?hl=en#sharing-files

**Comment by rusfearuth** [comment]
@agustinsivoplas Did you use the library with that PR?

**Comment by marcshilling** [comment]
Ok @rusfearuth I pulled this down and it seems to be working, but I have a couple questions before I merge:

1. Why did you add the `onActivityResult` method to `ImagePickerModule.java`? It seems to work the same with this commented out.

2. Can you explain the `provider_paths.xml` file to me? What is "app_images"?

**Comment by rusfearuth** [comment]
@marcshilling, I'm glad to hear it.

### About onActivityResult method

It's easy ). As you can see your `ImagePickerModule` implements `ActivityEventListener` which contains this method. That's way, I added this method to `ImagePickerModule` for avoiding compilation problems.

You can check it in **Android Studio**.

### About provider_paths.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="app_images" path="."/>
</paths>
```

It means that `app_images` is `.` into
```
/{path to external store}/Android/data/${applicationId}/files/
```

And files will be exist by the next URI `content://{applicationId}/app_images/{filename}`;

It's necessary for Android 7.0 and higher. You can read [this article](https://developer.android.com/training/secure-file-sharing/setup-sharing.html) for more details.

**Comment by marcshilling** [comment]
But `onActivityResult` is already defined with it's new signature:
```java
public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data)
```

The one you defined:
```java
public void onActivityResult(int requestCode, int resultCode, Intent data)
``` 
is from pre-React Native 0.33 I believe - which we no longer support. Do you agree? If so, no need to update the PR - I will remove.


As for the provider paths, I read the article you linked and it makes it seem like this is only for when you want to share files with another app. Is that really a requirement for this library? Everything with the image picker should exist within the parent app itself, right? Maybe I'm just not understanding...

**Comment by rusfearuth** [comment]
@marcshilling 
If you implement some interface **you must add methods of this interface**. [Read more here](https://docs.oracle.com/javase/tutorial/java/IandI/usinginterface.html)

You have different methods. As you can see `onActivityResult(int, int, Intent)` is declared in `ActivityEventListener` and `onActivityResult(Activity, int, int, Intent)` is another method. By another hand, ask your self 'Do I need `ActivityEventListener` or not'. If you don't need to implement `ActivityEventListener` interface, you'll be able to remove `onActivityResult(int, int, Intent)` and `implements ActivityEventListener`, but if you need this interface, you must declare `onActivityResult(int, int, Intent)`.

```
when you want to share files with another app.
```
Yes, exactly. Your app asks to save result of camera to app folder and give URI on shared resource. Now you should use it not only for sharing files. It's something like patch of security. [Read this](https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en). It said that you couldn't save you files any where on external store, your app had own folder and you had to save files there.

**Comment by rusfearuth** [comment]
@marcshilling Do you need any information for merging my PR?

**Comment by marcshilling** [comment]
Just haven't gotten around to it yet. Hopefully some night this week.

**Comment by ptomasroos** [comment]
Good job everyone involved!

**Comment by rusfearuth** [comment]
Thanks a lot!

**Comment by juddey** [comment]
Thank you from me too. :clap:

**Comment by asbjornenge** [comment]
@marcshilling possible to push a `0.24.1` for the < `0.40` crowd ?? :grimacing: :see_no_evil:

**Comment by rusfearuth** [comment]
@asbjornenge I think yes.

**Comment by asbjornenge** [comment]
@rusfearuth if at all possible, yeah :smiley: That would be awesome! I'm stuck on RN `0.37` running `0.24.0` of `react-native-image-picker`.

**Comment by manjeets12** [comment]
yeah its is breaking on my android phone(version 5.1) too, RN version 0.41.

working fine when choosing from  Library but crashing as soon as I tried to use camera

**Comment by rusfearuth** [comment]
@manjeets12 Could you create issue and give more information about RN version + `react-native-image-picker` version?

**Comment by asbjornenge** [comment]
@rusfearuth any news on a `0.24.1` release? Let me know if I can do anything to help out :smile: :+1:

**Comment by marcshilling** [comment]
0.24.1 is already live

**Comment by asbjornenge** [comment]
@marcshilling @rusfearuth finally found some time to give `0.24.1` a try, but still seeing:

```
android.os.FileUriExposedException: file:///storage/emulated/0/Pictures/image-3f1b8854-d3d0-444b-9825-fb6b2497cbf2.jpg exposed beyond app through ClipData.Item.getUri()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
	at android.net.Uri.checkFileUriExposed(Uri.java:2346)
	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:845)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:8941)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:8926)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
	at android.app.Activity.startActivityForResult(Activity.java:4225)
	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
	at android.app.Activity.startActivityForResult(Activity.java:4183)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
	at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:244)
	at com.imagepicker.ImagePickerModule$2.onClick(ImagePickerModule.java:158)
	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1136)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1156)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3121)
	at android.widget.AbsListView$3.run(AbsListView.java:4036)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
	at java.lang.Thread.run(Thread.java:761)
```

On `Android 7.1` :-/ Same or different error this?

**Comment by amonks** [comment]
upgrading to 0.24.1 *and* disabling StrictMode worked for me

**Pull request merged**
