### PR TITLE
added typescript typing definition

### PR DESCRIPTION
**Pull request by hktonylee**

### CODE REVIEW

**Comment by wcandillon** [comment]
@hktonylee Thank you so much for contributing this file. I hope it will be part of this repository.

**Comment by wcandillon** [comment]
@hktonylee In one of your stackoverflow answer, you seem to have a typing for `react-native-fbsdk`. Could I have access to this file?

**Comment by hktonylee** [comment]
@wcandillon Yes please refer to the [gist here](https://gist.github.com/hktonylee/21e9e3024250f9312ea058da7f03b522)

**Comment by wcandillon** [comment]
@hktonylee thank you :)

**Comment by marcshilling** [comment]
I'll merge this, but since I don't use TypeScript I'm going to leave it up to the community to maintain this should the API change at all going forward.

**Comment by wcandillon** [comment]
@marcshilling @hktonylee  I upgraded to the latest version and it works great, thank you!

**Pull request merged**
