### PR TITLE
[ios] Fixing support to png

### PR DESCRIPTION
**Pull request by gullitmiranda**

### CODE REVIEW

**Comment by marcshilling** [comment]
What's wrong with the existing code?

**Comment by gullitmiranda** [comment]
`[self.options objectForKey:@"imageFileType"]` is already an `NSString`.

stack: 
- react-native v0.33.0
- xCode 7.3.1
- iOS 9.3

**Comment by marcshilling** [comment]
Ok sure, but `objectForKey` returns an `NSObject`, not an `NSString`. Does the extra cast really matter? Was anything not working before or is this simply a syntax change?

**Comment by marcshilling** [comment]
No response.

**Comment by aksonov** [comment]
I'm getting crash 
```[NSTaggedPointerString stringValue]: unrecognized selector sent to instance 0xa00000000676e703```

when set 
```
    imageFileType: 'png',
```

what am I doing wrong?

**Comment by marcshilling** [comment]
Where are you setting this code?
`imageFileType: 'png',`

**Comment by aksonov** [comment]
Yes, all I want is to avoid any compression/modification of selected image.

**Comment by aksonov** [comment]
I'm trying to set it via options JS object

**Comment by aksonov** [comment]
@marcshilling Any chance that you could apply this PR to fix the problem?

**Comment by marcshilling** [comment]
I'll have to look into it. If you're just looking to avoid compression, if you specify `quality: 1` then it should not be compressed, but it will be a `.jpg` file.

**Comment by aksonov** [comment]
"f you're just looking to avoid compression"
@marcshilling It is not true. Image with quality: 1 is still processing and it results in much much large size than original (4x times!). Is it possible to get original image? I've tried to use 'originalUri' but it seems not accessible (starting with assets://) from React Native.

**Comment by nica0012** [comment]
@marcshilling Hi Marc, how come when adding a png image with a transparent background it is returned with a white background? Any way around this?

**Pull request closed without merging**
