### PR TITLE
convert video content:// URI into file:// URI for use with react-naive-video

### PR DESCRIPTION
**Pull request by DanlanNZ**
fixes issue #183 too

### CODE REVIEW

**Comment by yfuks** [comment]
Hi @DanlanNZ first of all thanks for the **PR** !

Well you just miss a litte thing. After trying your diff my app crash and i get the folowing stack :
```
E/AndroidRuntime(31574): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4, result=-1, data=null} to acti
vity {com.example/com.example.MainActivity}: java.lang.NullPointerException
E/AndroidRuntime(31574):        at android.app.ActivityThread.deliverResults(ActivityThread.java:3500)
E/AndroidRuntime(31574):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3543)
E/AndroidRuntime(31574):        at android.app.ActivityThread.access$1200(ActivityThread.java:159)
E/AndroidRuntime(31574):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
E/AndroidRuntime(31574):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31574):        at android.os.Looper.loop(Looper.java:176)
E/AndroidRuntime(31574):        at android.app.ActivityThread.main(ActivityThread.java:5419)
E/AndroidRuntime(31574):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(31574):        at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime(31574):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
E/AndroidRuntime(31574):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
E/AndroidRuntime(31574):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(31574): Caused by: java.lang.NullPointerException
E/AndroidRuntime(31574):        at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:347)
E/AndroidRuntime(31574):        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:188)
E/AndroidRuntime(31574):        at com.facebook.react.ReactInstanceManagerImpl.onActivityResult(ReactInstanceManagerImpl.java:597)
E/AndroidRuntime(31574):        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:180)
E/AndroidRuntime(31574):        at android.app.Activity.dispatchActivityResult(Activity.java:5563)
E/AndroidRuntime(31574):        at android.app.ActivityThread.deliverResults(ActivityThread.java:3496)
E/AndroidRuntime(31574):        ... 11 more
```

***Line 347*** you don't use your created file to retrieve the video but you use ```getData()```. You need to perfom the same thing as we do for image croping and image capture. (pass your file uri instead of getting the file from response)

Make the change and i will gladly accept your **PR** !

**Comment by yfuks** [comment]
No response i close. I added ```path``` to video response object that can be used in **react-native-video**

**Comment by DanlanNZ** [comment]
apologies @yfuks, had been meaning to fix this but wasn't quite sure where it was going wrong for you as it had been working for me. I am calling `ImagePickerManager.launchCamera` directly though.

will update this PR now so #183 can be closed. IMHO it doesn't make sense to pass a context specific URI back to the JS thread as it cannot be accessed from there

**Comment by zachrnolan** [comment]
@DanlanNZ @yfuks How would I go about using the video that was recorded with react-native-video?

**Comment by DanlanNZ** [comment]
@zachrnolan I haven't used this lib for a while and I was only using it for React Native Android dev, but from what I can remember the video path returned was relative to the [app context](http://stackoverflow.com/questions/3572463/what-is-context-on-android), which AFAIK can't be accessed from the JS thread. This PR attempted to overcome that issue by creating a new file (that is avaliable to the JS thread) to save the video contents in the same way images do

**Pull request closed without merging**
