### PR TITLE
Set source based on Platform

### PR DESCRIPTION
**Pull request by phoenixbox**
I thought the inclusion of a Platform check in the sample code might be helpful to those new to react-native

Thanks for the lib ❤️ 🚀 😄

### CODE REVIEW

**Comment by jakecraige** [comment]
Seeing this now, is there a chance this is actually confusing to people since it doesn't seem to be required to strip the file prefix? (at least I don't think so, I'm not an it works)

**Comment by marcshilling** [comment]
@jakecraige that part of the README is a little dated. If you can confirm that the same `uri` works on both iOS and Android I suppose we can remove it.

**Comment by phoenixbox** [comment]
Hmmm not sure, came across this a while ago so Im not 💯 that the url will work in Android without stripping the file prefix.

I mainly made this update because it was confusing to me to see `const source` be redefined without a conditional Platform check. If the url works without the prefix, then no worries rolling back this commit and settling on a single line 🌈

**Comment by marcshilling** [comment]
I can test it out when I get some time.

**Comment by phoenixbox** [comment]
awesome 🙌 , thanks for the lib 🌮  super helpful ✨

**Comment by jakecraige** [comment]
Sounds great. It's been working well for me without it which Is why I brought this up. Definitely test for yourself to make sure I'm not crazy thought 😄

**Comment by marcshilling** [comment]
Just confirmed @jakecraige, good call. Updating the README/Example project now!

**Pull request merged**
